apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: "2023-06-16T23:39:29Z"
  labels:
    kubernetes.io/metadata.name: cloro
  name: alvejante
  resourceVersion: "31023"
  uid: e602c074-6f31-4042-b3bd-547c1077072b
spec:
  limits:
  - default:
      cpu: 1
      memory: 100Mi
    defaultRequest:
      cpu: 0.5
      memory: 80Mi
    type: Container

